// Code generated by baton-sdk. DO NOT EDIT!!!
package config

import "reflect" 

type Mongodbatlas struct {
	Mongodbatlas_public_key string `mapstructure:"mongodbatlas_public_key"`
	Mongodbatlas_private_key string `mapstructure:"mongodbatlas_private_key"`
	Mongodbatlas_create_invite bool `mapstructure:"mongodbatlas_create_invite"`
	Mongodbatlas_enable_sync_database bool `mapstructure:"mongodbatlas_enable_sync_database"`
	Mongodbatlas_enable_mongo_driver bool `mapstructure:"mongodbatlas_enable_mongo_driver"`
	Mongodbatlas_enable_delete_database_user_with_read_only bool `mapstructure:"mongodbatlas_enable_delete_database_user_with_read_only"`
}

func (c* Mongodbatlas) findFieldByTag(tagValue string) (any, bool) {
	v := reflect.ValueOf(c).Elem() // Dereference pointer to struct
	t := v.Type()

	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		tag := field.Tag.Get("mapstructure")

		if tag == tagValue {
			return v.Field(i).Interface(), true
		}
	}
	return nil, false
}

func (c *Mongodbatlas) GetStringSlice(fieldName string) []string {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return []string{}
	}
	t, ok := v.([]string)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Mongodbatlas) GetString(fieldName string) string {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return ""
	}
	t, ok := v.(string)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Mongodbatlas) GetInt(fieldName string) int {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return 0
	}
	t, ok := v.(int)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Mongodbatlas) GetBool(fieldName string) bool {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return false
	}
	t, ok := v.(bool)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Mongodbatlas) GetStringMap(fieldName string) map[string]any {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return map[string]any{}
	}
	t, ok := v.(map[string]any)
	if !ok {
		panic("wrong type")
	}
	return t
}
