name: Tests
on: [workflow_dispatch, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    services:
      mongodb:
        image: mongo:4.4.6
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
          MONGO_INITDB_DATABASE: testdb
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build baton-mongodb
        run: go build ./cmd/baton-mongodb
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: mongo:latest
      - name: Run baton-mongodb
        env:
          BATON_PUBLIC_KEY: 'jyzkthbd'
          BATON_PRIVATE_KEY: '3b14d374-68f7-4eb8-be60-fd3fd893743e'
        run: ./baton-mongodb
      - name: Run baton-mongodb v2
        run: |
          echo "Running integration Tests"
          ./baton-mongodb --public-key jyzkthbd --private-key 3b14d374-68f7-4eb8-be60-fd3fd893743e
    # ...  